source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/crspybits/Specs.git'

use_frameworks!

target 'SMCoreLib_Example' do
  pod 'SMCoreLib', :path => '../'
  # pod 'SMCoreLib'

  target 'SMCoreLib_Tests' do
    inherit! :search_paths
  end
end
